---
- name: Provision Ec2 instance & install XX
  hosts: localhost
  gather_facts: false
  roles:
    - ecr_setup
   

- name: Configuration of Ec2 instances
  hosts: launched_ec2_instances
  gather_facts: true
  roles:
    - common
    - docker     



    